default['go_cd']['server_download_url'] = 'http://download.go.cd/gocd-deb/go-server-14.2.0-377.deb'
default['go_cd']['agent_download_url'] = 'http://download.go.cd/gocd/go-agent-14.4.0-1356.zip'
default['go_cd']['user'] = 'go'
default['go_cd']['group'] = 'go'
default['go_cd']['server_ip'] = 'localhost'
